name: Dummy

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      head_sha:
        required: true
        type: string
      comment_body:
        required: true
        type: string
      anthropic_api_key:
        required: true
        type: string
      gh_pat:
        required: false
        type: string

concurrency:
  group: claude-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: false

jobs:
  claude:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          repository: ${{ inputs.owner }}/${{ inputs.repo }}
          ref: ${{ inputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        env:
          GH_TOKEN: ${{ inputs.gh_pat }}
        with:
          anthropic_api_key: ${{ inputs.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_args: "--allowedTools Bash,Read,Write,Edit,Glob,Grep"


  # notify-result:
  #   if: ${{ always() }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: POST success callback
  #       run: |
  #         curl -X POST "$CALLBACK_URL" \
  #           -H "Content-Type: application/json" \
  #           -d '{
  #             "workflow": "Build",
  #             "run_id": "'"${{ github.event.workflow_run.id }}"'",
  #             "conclusion": "success"
  #           }'
  #       env:
  #         CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
